Repository RainbowAllRounders/GoalKeeper, pull requests merged in 2024-04, with the labels that each got.

#1 이슈 템플릿 설정
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: ⚙ Setting

#2 Delete .github/ISSUE_TEMPLATE directory
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: ⚙ Setting

#3 프로젝트 설정 및 패키지 구조 구축
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/checksums/md5-checksums.bin
  .gradle/8.7/checksums/sha1-checksums.bin
  .gradle/8.7/dependencies-accessors/gc.properties
  .gradle/8.7/executionHistory/executionHistory.bin
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileChanges/last-build.bin
  .gradle/8.7/fileHashes/fileHashes.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/fileHashes/resourceHashesCache.bin
  .gradle/8.7/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  build/reports/tests/test/classes/com.allrounders.goalkeeper.GoalkeeperApplicationTests.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/com.allrounders.goalkeeper.html
  build/resolvedMainClassName
  build/resources/main/application.properties
  build/test-results/test/TEST-com.allrounders.goalkeeper.GoalkeeperApplicationTests.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/bootJar/MANIFEST.MF
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  build/tmp/jar/MANIFEST.MF
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/allrounders/goalkeeper/GoalkeeperApplication.java
  src/main/java/com/allrounders/goalkeeper/config/SwaggerConfig.java
  src/main/java/com/allrounders/goalkeeper/controller/MemberController.java
  src/main/java/com/allrounders/goalkeeper/controller/advice/CustomRestAdvice.java
  src/main/java/com/allrounders/goalkeeper/domain/Member.java
  src/main/java/com/allrounders/goalkeeper/dto/MemberDTO.java
  src/main/java/com/allrounders/goalkeeper/repository/MemberRepository.java
  src/main/java/com/allrounders/goalkeeper/service/MemberService.java
  src/main/java/com/allrounders/goalkeeper/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/script.js
  src/test/java/com/allrounders/goalkeeper/GoalkeeperApplicationTests.java
  src/test/java/com/allrounders/goalkeeper/repository/MemberRepositoryTests.java
  src/test/java/com/allrounders/goalkeeper/service/MemberServiceTests.java
Labels: ⚙ Setting, 💾 Server

#4 Update issue templates
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: ⚙ Setting, 📃 Docs

#5 @Config 설정
  src/main/java/com/allrounders/goalkeeper/config/CustomServletConfig.java
  src/main/java/com/allrounders/goalkeeper/config/RootConfig.java
  src/main/java/com/allrounders/goalkeeper/service/MemberServiceImpl.java
Labels: ⚙ Setting, 💾 Server

#6 gitignore 파일 설정
  .gitignore
Labels: ⚙ Setting, 💾 Server

#7 gaannini_gitTest
  src/main/java/com/allrounders/goalkeeper/domain/Goal.java
Labels: ✅ Test

#8 Commit Test_Base Entity 생성
  src/main/java/com/allrounders/goalkeeper/domain/BaseEntity.java
Labels: ✅ Test

#9 깃허브 테스트
  src/main/java/com/allrounders/goalkeeper/controller/MemberController.java
Labels: 💾 Server
